### ISSUE TITLE
animal ID is not updated properly

### ISSUE THREAD

**Issue by XX-Yin** [AllenNeuralDynamics/dynamic-foraging-task#1449]
I recently ran into one issue. 

The mouse ID was changed in the UI, but it's not changed in the json file. I believe this is because the asynchronous update of behavior session model and the UI widgets, which happened before for the Task.

**Comment by micahwoodard** [comment]
I don't really know do you have any more details or log files or anything?

**Comment by alexpiet** [comment]
What rig was this on? When did this happen? Was the mouse on the schedule?

**Comment by ellahiltonvano** [comment]
@XX-Yin can you follow up on this issue?

**Comment by XX-Yin** [comment]
@micahwoodard This happens when I load multiple sessions from different mice in succession. For example, loading mouse 1 and then loading mouse 2, and then starting the session. The data will be saved in a folder of mouse 1 instead of mouse 2.

**Comment by micahwoodard** [comment]
Oh I bet it has something to do with updating the text box but since it's doing it programmatically, the textChanged signal isn't emitted. Would probably be fixed by updating the session model at the end of the load function

**Comment by ellahiltonvano** [comment]
@XX-Yin @micahwoodard are there any action items for this issue?

**Comment by ellahiltonvano** [comment]
@XX-Yin @micahwoodard are we still planning to update this? If so, can I assign one of you?

**Comment by ellahiltonvano** [comment]
@XX-Yin is this something you're planning to update?

**Comment by XX-Yin** [comment]
@ellahiltonvano This is still an issue related to the asynchronous update of behavior_session_model that we need to address, but I don't have bandwidth to fix it.

**Comment by ellahiltonvano** [comment]
@XX-Yin if you think this is a priority could you please open a SIPE ticket?

**Comment by XX-Yin** [comment]
> [@XX-Yin](https://github.com/XX-Yin) if you think this is a priority could you please open a SIPE ticket?

@ellahiltonvano I think I can fix this some time.

**Comment by ellahiltonvano** [comment]
@XX-Yin checking in on this, can it be closed since it was opened over 1 year ago and there has been no fix?
