### ISSUE TITLE
Save button is stateful

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/dynamic-foraging-task#1479]
The save button stays depressed even when loading from session save files. Should the save button emit a signal and not stay depressed? Seems like an extra piece of state that can only lead to heartache like #1394.

**Comment by alexpiet** [comment]
Yes, completely agree. This has been noticed before:
- https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/304
- https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/280
Those issues were closed because @micahwoodard's major update should resolve this issue by encapsulating important parameters into data models, rather than just reloading the state of the GUI. (https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/800)
@micahwoodard Do you agree with that assessment?

**Comment by micahwoodard** [comment]
@alexpiet yes although I haven't yet updated the manual loading function, only loading through slims. When manually loading in a mouse, do we want the user to point towards a folder that has the necessary pydantic models and then only load in and update parameters pertaining to the models? Or do we also want to update all of the widget values found in the behavior json?

**Comment by alexpiet** [comment]
I think we want the state of the GUI to be the same whether the mouse is loaded from SLIMS or the local data

**Comment by galenlynch** [comment]
Will slims allow for off-curriculum  mice?

**Comment by galenlynch** [comment]
> Those issues were closed because [@micahwoodard](https://github.com/micahwoodard)'s major update should resolve this issue by encapsulating important parameters into data models, rather than just reloading the state of the GUI. ([#800](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/800))

That will prevent the state from living past a session, but I still don't see why the button should have any state.

**Comment by ellahiltonvano** [comment]
@alexpiet will this issue be addressed before we switch to Micah's update or can this be closed?
